#!/usr/bin/env python3
"""Dump the POMDP generative model (A, B, C, D) for the paper appendix.

Builds the default-configuration agent, extracts the exact numeric matrices via
``ActiveInferencePOMDPAgent.dump_matrices()``, and writes:

  * ``results/generative_model.json`` -- full A/B/C/D as nested lists.
  * ``paper/figures/generative_model.tex`` -- LaTeX for the appendix: the three
    action-conditioned B[0] transition matrices, the C preference vectors, the D
    priors, and representative conditional slices of the A likelihood tensors
    (the full A is generated parametrically; representative slices plus the
    closed form fully specify it).

Usage:
    python -m scripts.dump_generative_model
"""

import json
from pathlib import Path

import numpy as np

from src.active_inference.pomdp_agent import (
    ActiveInferencePOMDPAgent, ACTION_NAMES,
    IMPORTANCE_LABELS, CAUSAL_LABELS, ROLE_LABELS,
)


def _mat(rows, fmt="{:.3f}"):
    return " \\\\\n".join(" & ".join(fmt.format(x) for x in row) for row in rows)


def _vec(v, fmt="{:.3f}"):
    return " & ".join(fmt.format(x) for x in v)


def _bmatrix(M, fmt="{:.3f}"):
    """Render a 2D array as a LaTeX bmatrix body (no environment)."""
    return _mat(M, fmt)


def main():
    base = Path(__file__).parent.parent
    agent = ActiveInferencePOMDPAgent(n_layers=26)
    agent.initialize()
    md = agent.dump_matrices()

    results = base / "results" / "generative_model.json"
    results.parent.mkdir(exist_ok=True)
    with open(results, "w") as f:
        json.dump(md, f, indent=2)

    A = [np.array(a) for a in md["A"]]
    B = [np.array(b) for b in md["B"]]
    C = [np.array(c) for c in md["C"]]
    D = [np.array(d) for d in md["D"]]

    cfg = md["config"]
    lines = []
    lines.append("% Auto-generated by scripts/dump_generative_model.py")
    lines.append("% Exact numeric generative model (A, B, C, D) for the default agent.")
    lines.append("")

    # --- B[0]: action-conditioned importance transitions ---
    lines.append("The transition model $\\mathbf{B}^{(0)}$ for the importance factor "
                 "is action-conditioned. Columns are the current importance state, "
                 "rows the next state, for each intervention action:")
    for a_idx, a_name in enumerate(ACTION_NAMES):
        Ba = B[0][:, :, a_idx]
        lines.append("\\[")
        lines.append(f"\\mathbf{{B}}^{{(0)}}_{{\\text{{{a_name.replace('_',' ')}}}}} = "
                     "\\begin{bmatrix}")
        lines.append(_mat(Ba))
        lines.append("\\end{bmatrix}")
        lines.append("\\]")

    # --- B[1], B[2]: identity transitions for intrinsic factors ---
    lines.append("The layer-role factor $\\mathbf{B}^{(1)}$ and the causal-strength "
                 "factor $\\mathbf{B}^{(2)}$ are intrinsic properties with "
                 "identity (single-action) dynamics:")
    lines.append("\\[")
    lines.append("\\mathbf{B}^{(1)} = \\begin{bmatrix}" + _mat(B[1][:, :, 0]) + "\\end{bmatrix},"
                 "\\qquad \\mathbf{B}^{(2)} = \\begin{bmatrix}" + _mat(B[2][:, :, 0]) + "\\end{bmatrix}.")
    lines.append("\\]")

    # --- C preference vectors (stacked vertically to fit the column) ---
    lines.append("The preference vectors $\\mathbf{C}$ encode log-preferences over "
                 "observations (higher KL and activation are more informative):")
    lines.append("\\[")
    lines.append("\\begin{aligned}")
    lines.append("\\mathbf{C}^{(\\mathrm{KL})} &= \\begin{bmatrix}" + _vec(C[0]) + "\\end{bmatrix}, &\\quad")
    lines.append("\\mathbf{C}^{(\\mathrm{act})} &= \\begin{bmatrix}" + _vec(C[1]) + "\\end{bmatrix}, \\\\")
    lines.append("\\mathbf{C}^{(\\mathrm{conn})} &= \\begin{bmatrix}" + _vec(C[2]) + "\\end{bmatrix}. &")
    lines.append("\\end{aligned}")
    lines.append("\\]")

    # --- D priors (stacked vertically to fit the column) ---
    lines.append("The priors $\\mathbf{D}$ over the three hidden-state factors are:")
    lines.append("\\[")
    lines.append("\\begin{aligned}")
    lines.append("\\mathbf{D}^{(\\mathrm{imp})} &= \\begin{bmatrix}" + _vec(D[0]) + "\\end{bmatrix}, &\\quad")
    lines.append("\\mathbf{D}^{(\\mathrm{role})} &= \\begin{bmatrix}" + _vec(D[1]) + "\\end{bmatrix}, \\\\")
    lines.append("\\mathbf{D}^{(\\mathrm{causal})} &= \\begin{bmatrix}" + _vec(D[2]) + "\\end{bmatrix}. &")
    lines.append("\\end{aligned}")
    lines.append("\\]")

    # --- A[0]: KL likelihood (role-independent) ---
    role_mid = A[0].shape[2] // 2
    lines.append("The observation likelihood $\\mathbf{A}^{(0)}$ for the KL modality is "
                 "independent of layer role; each row gives "
                 "$P(o^{\\mathrm{KL}}\\mid s_{\\mathrm{imp}}, s_{\\mathrm{causal}})$ "
                 "over the four KL levels (negligible, small, medium, large):")
    lines.append("\\[")
    lines.append("\\begin{array}{ll|cccc}")
    lines.append("\\text{imp.} & \\text{causal} & \\text{neg.} & \\text{small} & \\text{med.} & \\text{large} \\\\ \\hline")
    for s0 in range(A[0].shape[1]):
        for s2 in range(A[0].shape[3]):
            col = A[0][:, s0, role_mid, s2]
            lines.append(f"\\text{{{IMPORTANCE_LABELS[s0]}}} & \\text{{{CAUSAL_LABELS[s2]}}} & "
                         + " & ".join(f"{x:.3f}" for x in col) + " \\\\")
    lines.append("\\end{array}")
    lines.append("\\]")

    # --- A[1]: activation likelihood (depends on importance and role) ---
    lines.append("The activation modality $\\mathbf{A}^{(1)}$ depends on importance and "
                 "layer role (it is independent of causal strength); each row gives "
                 "$P(o^{\\mathrm{act}}\\mid s_{\\mathrm{imp}}, s_{\\mathrm{role}})$ "
                 "over the four activation levels (inactive, low, moderate, high):")
    lines.append("\\[")
    lines.append("\\begin{array}{ll|cccc}")
    lines.append("\\text{imp.} & \\text{role} & \\text{inact.} & \\text{low} & \\text{mod.} & \\text{high} \\\\ \\hline")
    n_role = A[1].shape[2]
    for s0 in range(A[1].shape[1]):
        for s1 in range(n_role):
            col = A[1][:, s0, s1, 0]
            role_lbl = ROLE_LABELS[s1] if n_role == 3 else f"r{s1}"
            lines.append(f"\\text{{{IMPORTANCE_LABELS[s0]}}} & \\text{{{role_lbl}}} & "
                         + " & ".join(f"{x:.3f}" for x in col) + " \\\\")
    lines.append("\\end{array}")
    lines.append("\\]")

    # --- A[2]: connectivity likelihood (depends on role and causal; imp-independent) ---
    lines.append("The connectivity modality $\\mathbf{A}^{(2)}$ depends on layer role and "
                 "causal strength (it is independent of importance); each row gives "
                 "$P(o^{\\mathrm{conn}}\\mid s_{\\mathrm{role}}, s_{\\mathrm{causal}})$ "
                 "over the three connectivity levels (sparse, moderate, dense):")
    lines.append("\\[")
    lines.append("\\begin{array}{ll|ccc}")
    lines.append("\\text{role} & \\text{causal} & \\text{sparse} & \\text{mod.} & \\text{dense} \\\\ \\hline")
    for s1 in range(A[2].shape[2]):
        for s2 in range(A[2].shape[3]):
            col = A[2][:, 0, s1, s2]
            role_lbl = ROLE_LABELS[s1] if A[2].shape[2] == 3 else f"r{s1}"
            lines.append(f"\\text{{{role_lbl}}} & \\text{{{CAUSAL_LABELS[s2]}}} & "
                         + " & ".join(f"{x:.3f}" for x in col) + " \\\\")
    lines.append("\\end{array}")
    lines.append("\\]")

    # --- Dirichlet concentration prior ---
    lines.append("The observation model is learned online. The Dirichlet "
                 "concentration parameters are initialised as $\\mathbf{a}^{(m)} = "
                 "10\\,\\mathbf{A}^{(m)}$ for each modality $m$ (a concentration of ten "
                 "times the prior likelihood), and updated with learning rate "
                 f"$\\eta = {cfg['lr_pA']:.1f}$ after every intervention.")

    out = base / "paper" / "figures" / "generative_model.tex"
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {results}")
    print(f"Wrote {out}")
    print(f"A shapes: {[a.shape for a in A]}")
    print(f"B shapes: {[b.shape for b in B]}")


if __name__ == "__main__":
    main()
