#!/usr/bin/env python3
"""Dump the POMDP generative model (A, B, C, D) for the paper appendix.

Builds the default-configuration agent, extracts the exact numeric matrices via
``ActiveInferencePOMDPAgent.dump_matrices()``, and writes:

  * ``results/generative_model.json`` -- full A/B/C/D as nested lists.
  * ``paper/figures/generative_model.tex`` -- LaTeX for the appendix: the three
    action-conditioned B[0] transition matrices, the C preference vectors, the D
    priors, and representative conditional slices of the A likelihood tensors
    (the full A is generated parametrically; representative slices plus the
    closed form fully specify it).

Usage:
    python -m scripts.dump_generative_model
"""

import json
from pathlib import Path

import numpy as np

from src.active_inference.pomdp_agent import (
    ActiveInferencePOMDPAgent, ACTION_NAMES,
    IMPORTANCE_LABELS, CAUSAL_LABELS,
)


def _mat(rows, fmt="{:.3f}"):
    return " \\\\\n".join(" & ".join(fmt.format(x) for x in row) for row in rows)


def _vec(v, fmt="{:.3f}"):
    return " & ".join(fmt.format(x) for x in v)


def main():
    base = Path(__file__).parent.parent
    agent = ActiveInferencePOMDPAgent(n_layers=26)
    agent.initialize()
    md = agent.dump_matrices()

    results = base / "results" / "generative_model.json"
    results.parent.mkdir(exist_ok=True)
    with open(results, "w") as f:
        json.dump(md, f, indent=2)

    A = [np.array(a) for a in md["A"]]
    B = [np.array(b) for b in md["B"]]
    C = [np.array(c) for c in md["C"]]
    D = [np.array(d) for d in md["D"]]

    lines = []
    lines.append("% Auto-generated by scripts/dump_generative_model.py")
    lines.append("% Exact numeric generative model (A, B, C, D) for the default agent.")
    lines.append("")

    # --- B[0]: action-conditioned importance transitions ---
    lines.append("\\paragraph{Transition model $\\mathbf{B}^{(0)}$ (importance factor).}")
    lines.append("Columns are the current importance state, rows the next state, "
                 "for each intervention action:")
    for a_idx, a_name in enumerate(ACTION_NAMES):
        Ba = B[0][:, :, a_idx]
        lines.append("\\[")
        lines.append(f"\\mathbf{{B}}^{{(0)}}_{{\\text{{{a_name.replace('_',' ')}}}}} = "
                     "\\begin{bmatrix}")
        lines.append(_mat(Ba))
        lines.append("\\end{bmatrix}")
        lines.append("\\]")

    # --- C preference vectors (stacked vertically to fit the column) ---
    lines.append("\\paragraph{Preferences $\\mathbf{C}$ (log-preference over observations).}")
    lines.append("\\[")
    lines.append("\\begin{aligned}")
    lines.append("\\mathbf{C}^{(\\mathrm{KL})} &= \\begin{bmatrix}" + _vec(C[0]) + "\\end{bmatrix}, &\\quad")
    lines.append("\\mathbf{C}^{(\\mathrm{act})} &= \\begin{bmatrix}" + _vec(C[1]) + "\\end{bmatrix}, \\\\")
    lines.append("\\mathbf{C}^{(\\mathrm{conn})} &= \\begin{bmatrix}" + _vec(C[2]) + "\\end{bmatrix}. &")
    lines.append("\\end{aligned}")
    lines.append("\\]")

    # --- D priors (stacked vertically to fit the column) ---
    lines.append("\\paragraph{Priors $\\mathbf{D}$ over hidden states.}")
    lines.append("\\[")
    lines.append("\\begin{aligned}")
    lines.append("\\mathbf{D}^{(\\mathrm{imp})} &= \\begin{bmatrix}" + _vec(D[0]) + "\\end{bmatrix}, &\\quad")
    lines.append("\\mathbf{D}^{(\\mathrm{role})} &= \\begin{bmatrix}" + _vec(D[1]) + "\\end{bmatrix}, \\\\")
    lines.append("\\mathbf{D}^{(\\mathrm{causal})} &= \\begin{bmatrix}" + _vec(D[2]) + "\\end{bmatrix}. &")
    lines.append("\\end{aligned}")
    lines.append("\\]")

    # --- A[0] representative slice: KL likelihood vs (importance, causal) at middle role ---
    role_mid = A[0].shape[2] // 2
    lines.append("\\paragraph{Observation likelihood $\\mathbf{A}^{(0)}$ (KL modality).}")
    lines.append("$\\mathbf{A}^{(0)}$ does not depend on layer role; each column below is "
                 "$P(o^{\\mathrm{KL}}\\mid s_{\\mathrm{imp}}, s_{\\mathrm{causal}})$ "
                 "(KL levels: negligible/small/medium/large):")
    # Build a table over (importance x causal) -> 4-vector
    lines.append("\\[")
    lines.append("\\begin{array}{ll|cccc}")
    lines.append("\\text{importance} & \\text{causal} & \\text{neg.} & \\text{small} & \\text{med.} & \\text{large} \\\\ \\hline")
    for s0 in range(A[0].shape[1]):
        for s2 in range(A[0].shape[3]):
            col = A[0][:, s0, role_mid, s2]
            lines.append(f"\\text{{{IMPORTANCE_LABELS[s0]}}} & \\text{{{CAUSAL_LABELS[s2]}}} & "
                         + " & ".join(f"{x:.3f}" for x in col) + " \\\\")
    lines.append("\\end{array}")
    lines.append("\\]")

    out = base / "paper" / "figures" / "generative_model.tex"
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {results}")
    print(f"Wrote {out}")
    print(f"A shapes: {[a.shape for a in A]}")
    print(f"B shapes: {[b.shape for b in B]}")


if __name__ == "__main__":
    main()
